/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

public class AccountPage extends javax.swing.JFrame {

    /**
     * Creates new form AccountPage
     */
    public AccountPage() {
        //balance = 0;
        //accNumber = 10023;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountNumberLabel = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceAmount = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Withdraw = new javax.swing.JPanel();
        enterWithdrawAmountLabel = new javax.swing.JLabel();
        withdrawAmount = new javax.swing.JSpinner();
        withdrawButton = new javax.swing.JButton();
        Deposit = new javax.swing.JPanel();
        enterAmountDeposit = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        depositAmount = new javax.swing.JSpinner();
        Loan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account");

        accountNumberLabel.setText("Account No:");

        accountNumber.setText(String.valueOf(accNumber)
        );

        balanceLabel.setText("Balance:");

        balanceAmount.setText(String.valueOf(balance));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N

        enterWithdrawAmountLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        enterWithdrawAmountLabel.setText("Enter Amount");

        withdrawAmount.setModel(new SpinnerNumberModel(0.0,0.0,999_999_999.99,1));

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WithdrawLayout = new javax.swing.GroupLayout(Withdraw);
        Withdraw.setLayout(WithdrawLayout);
        WithdrawLayout.setHorizontalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterWithdrawAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        WithdrawLayout.setVerticalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(enterWithdrawAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Withdraw", Withdraw);

        enterAmountDeposit.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        enterAmountDeposit.setText("Enter Amount");

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        depositAmount.setModel(new SpinnerNumberModel(0.0,0.0,999_999_999.99,1));

        javax.swing.GroupLayout DepositLayout = new javax.swing.GroupLayout(Deposit);
        Deposit.setLayout(DepositLayout);
        DepositLayout.setHorizontalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositLayout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(DepositLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterAmountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DepositLayout.setVerticalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(enterAmountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deposit", Deposit);

        javax.swing.GroupLayout LoanLayout = new javax.swing.GroupLayout(Loan);
        Loan.setLayout(LoanLayout);
        LoanLayout.setHorizontalGroup(
            LoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        LoanLayout.setVerticalGroup(
            LoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Loan", Loan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(balanceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(balanceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        Main.accountPage.setVisible(false);
        Main.userPage.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        try {
            withdrawAmount.commitEdit();
            double amount = (double)withdrawAmount.getValue();
            System.out.println("Amount printed: "+amount);
            if(amount<=0){
                JOptionPane.showMessageDialog(Main.accountPage,
                        "Enter a value more than 0",
                        "Very small value",
                        JOptionPane.ERROR_MESSAGE);
            }else{
                try {
                    Statement st = Main.conn.createStatement();
                    st.executeUpdate("UPDATE ACCOUNT SET BALANCE = BALANCE - " + amount);
                    JOptionPane.showMessageDialog(Main.accountPage,
                        "Withdrawn Rs." + amount +" ",
                        "Success",
                        JOptionPane.PLAIN_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(AccountPage.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(Main.accountPage,
                        ex.toString(),
                        "SQL Error",
                        JOptionPane.ERROR_MESSAGE);
                }
                setAccountDetails(String.valueOf(accNumber),userName);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(withdrawAmount,
            "Enter a Proper value",
            "Error Occured",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        try {
            depositAmount.commitEdit();
            double amount = (double)depositAmount.getValue();
            System.out.println("Amount printed: "+amount);
            if(amount<=0){
                JOptionPane.showMessageDialog(Main.accountPage,
                        "Enter a value more than 0",
                        "Very small value",
                        JOptionPane.ERROR_MESSAGE);
            }else{
                try {
                    Statement st = Main.conn.createStatement();
                    st.executeUpdate("UPDATE ACCOUNT SET BALANCE = BALANCE + " + amount);
                    JOptionPane.showMessageDialog(Main.accountPage,
                        "Deposited Rs." + amount +" ",
                        "Success",
                        JOptionPane.PLAIN_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(AccountPage.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(Main.accountPage,
                        ex.toString(),
                        "SQL Error",
                        JOptionPane.ERROR_MESSAGE);
                }
                setAccountDetails(String.valueOf(accNumber),userName);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(withdrawAmount,
            "Enter a Proper value",
            "Error Occured",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_depositButtonActionPerformed

    public void setAccountDetails(String accNumber,String userName){
        try{

            Statement st = Main.conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM ACCOUNT WHERE Accountno = "+accNumber);
            if(rs.next()){
                this.balance = rs.getInt("BALANCE");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        this.accNumber = Integer.parseInt(accNumber);
        this.accountNumber.setText(String.valueOf(accNumber));
        this.balanceAmount.setText(String.valueOf(balance));
        this.userName = userName;
        this.repaint();
        System.out.println(balance+"  "+accNumber);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountPage().setVisible(true);
            }
        });
    }
    
    
    private int balance;
    private int accNumber;
    private String userName;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Deposit;
    private javax.swing.JPanel Loan;
    private javax.swing.JPanel Withdraw;
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel balanceAmount;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JSpinner depositAmount;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel enterAmountDeposit;
    private javax.swing.JLabel enterWithdrawAmountLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner withdrawAmount;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
