
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form BankApplication
     */
    public LoginPage() {
        try{
            st = Main.conn.createStatement();
        }
        catch(java.sql.SQLException e){
            e.printStackTrace();
        }
        initComponents();
        //this.getContentPane().add(new Login());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        loginText = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Application");

        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginText.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 24)); // NOI18N
        loginText.setText("Login");
        loginText.setToolTipText("");

        usernameLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        usernameLabel.setText("Username");

        userNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusGained(evt);
            }
        });
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        passwordLabel.setText("Password");

        loginButton.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginError.setVisible(false);
        loginError.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        loginError.setForeground(new java.awt.Color(235, 28, 28));
        loginError.setText("Invalid username or password.");
        loginError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginErrorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginError, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginError.setVisible(false);
        String username = userNameTextField.getText();
        char[] password = passwordField.getPassword();
        boolean credFlag = checkCred(username,password);
        String userType= "";
        passwordField.setText("");
        if(credFlag){
            
            // find the user type here
            try{
                ResultSet rs = st.executeQuery("SELECT USERTYPE FROM LOGINTAB WHERE USERNAME = \""+username+"\"");                
                if(rs.next()){
                    userType = rs.getString("USERTYPE");
                }
            }
            catch(java.sql.SQLException e){
                e.printStackTrace();
            }
            if(userType.equals( "CUST")){
                Main.userPage = new UserPage(username);
                Main.userPage.setVisible(true);
                this.setVisible(false);
            }else if(userType.equals("BANKER")){
                Main.bankerPage = new BankerPage();
                Main.bankerPage.setVisible(true);
                this.setVisible(false);
            }
        }
        else{
            loginError.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginErrorMouseClicked
        // TODO add your handling code here:
        loginError.setVisible(false);
    }//GEN-LAST:event_loginErrorMouseClicked

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void userNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusGained
        // TODO add your handling code here:
        userNameTextField.setText("ARAVIND_NAIR");
        passwordField.setText("SUNSHINE$");
    }//GEN-LAST:event_userNameTextFieldFocusGained

    private static boolean checkCred(String username, char[] password){
        boolean rtVal = false;
        String db_username="";
        String db_password = "";
        try{
            ResultSet rs = st.executeQuery("SELECT PASSWORD FROM LOGINTAB WHERE USERNAME="+"\""+username+"\"");
            if(rs.next()){
                //db_username = rs.getString("USERNAME");
                db_password = rs.getString("PASSWORD");
            }
            else{
                return false;
            }
            rs.close();
            
            char[] passwordChars = db_password.toCharArray();
            if(passwordChars.length != password.length) 
                return false;
            
            for(int i = 0; i<passwordChars.length;i++)
                if(passwordChars[i] != password[i]) 
                    return false;
            
            System.out.println(db_username+" "+db_password);
            return true;
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return rtVal;
    }
    /**
     * @param args the command line arguments
     */
    private static Statement st;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginError;
    private javax.swing.JLabel loginText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
