/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */

import java.awt.event.ActionEvent;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public UserPage(String username) {
        this.username = username;
        accountList = new ArrayList<Integer>();
        getDetails();
        initComponents();
    }

    private void getDetails(){
        // Using username getDetails from the database
        try{
            Statement st = Main.conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM CUSTOMER WHERE USERNAME = \""+username+"\"");
            if(rs.next()){
                name = rs.getString("CUS_NAME");
                address = rs.getString("CUS_ADDRESS");
                customerId = rs.getInt("CUSTOMER_ID");
            }
            rs = st.executeQuery("SELECT ACCOUNTNO, BALANCE FROM CUSTOMER C JOIN ACCOUNT A ON C.CUSTOMER_ID = A.CUSTOMER_ID WHERE C.CUSTOMER_ID = " + customerId);
            int i =0;
            while(rs.next()){
                accountList.add(rs.getInt("ACCOUNTNO"));
                i++;
            }
            numAccounts = i;
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JLabel();
        userAccountInfo = new javax.swing.JScrollPane();
        userAccountPanel = new javax.swing.JPanel();
        selectAccountText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        nameField.setText(name);

        nameLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        nameLabel.setText("Name:");

        addressLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        addressLabel.setText("Address:");

        addressText.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        addressText.setText(address
        );

        userAccountInfo.setAutoscrolls(true);

        userAccountPanel.setLayout(new java.awt.GridLayout(numAccounts, 0));
        javax.swing.JButton button;
        for(int i = 0; i<numAccounts; i++){
            button =  new javax.swing.JButton();
            button.setText(""+accountList.get(i));
            button.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt){
                    accountButtonActionPerformed(evt);
                }
            });
            userAccountPanel.add(button);

        }
        userAccountPanel.repaint();
        userAccountInfo.setViewportView(userAccountPanel);

        selectAccountText.setText("Select the required account:");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAccountText, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(selectAccountText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Main.userPage.setVisible(false);
        Main.userPage = null;
        Main.accountPage = null;
        Main.loginPage.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed
    public void accountButtonActionPerformed(java.awt.event.ActionEvent evt){
        javax.swing.JButton accountButton = (javax.swing.JButton)evt.getSource();
        String accountNumber = accountButton.getText();
        if (accountNumber == null) System.out.println("Account Button retuned NuLL");
        if( Main.accountPage == null){
            Main.accountPage = new AccountPage();
        }
        Main.accountPage.setAccountDetails(accountNumber,username);
        Main.accountPage.repaint();
        Main.accountPage.setVisible(true);
        Main.userPage.setVisible(false);
        
    }
    
    private String username;
    private String name;
    private String address;
    private int customerId;
    private int numAccounts;
    private ArrayList<Integer> accountList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressText;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel selectAccountText;
    private javax.swing.JScrollPane userAccountInfo;
    private javax.swing.JPanel userAccountPanel;
    // End of variables declaration//GEN-END:variables
}
