/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */

import java.awt.event.ActionEvent;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public UserPage(String username) {
        this.username = username;
        accountListModel = new DefaultComboBoxModel<String>();
        getDetails();
        initComponents();
    }

    private void getDetails(){
        // Using username getDetails from the database
        accountListModel.addElement("Select Account Number");
        try{
            Statement st = Main.conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM CUSTOMER WHERE USERNAME = \""+username+"\"");
            if(rs.next()){
                name = rs.getString("CUS_NAME");
                address = rs.getString("CUS_ADDRESS");
                customerId = rs.getInt("CUSTOMER_ID");
            }
            rs = st.executeQuery("SELECT ACCOUNTNO, BALANCE FROM CUSTOMER C JOIN ACCOUNT A ON C.CUSTOMER_ID = A.CUSTOMER_ID WHERE C.CUSTOMER_ID = " + customerId);
            int i =0;
            while(rs.next()){
                accountListModel.addElement(String.valueOf(rs.getInt("ACCOUNTNO")));
                i++;
            }
            numAccounts = i;
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JLabel();
        selectAccountText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        accountComboBox = new javax.swing.JComboBox<>();
        openAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome User!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nameField.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        nameField.setText(name);

        nameLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        nameLabel.setText("Name:");

        addressLabel.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        addressLabel.setText("Address:");

        addressText.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        addressText.setText(address
        );

        selectAccountText.setText("Select the required account:");

        logoutButton.setBackground(new java.awt.Color(255, 94, 94));
        logoutButton.setForeground(new java.awt.Color(26, 26, 26));
        logoutButton.setText("Logout");
        logoutButton.setToolTipText("Logout from current session");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        accountComboBox.setModel(accountListModel);

        openAccount.setText("Continue");
        openAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(openAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectAccountText, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(selectAccountText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(openAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(171, 171, 171))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Main.userPage.setVisible(false);
        Main.userPage = null;
        Main.accountPage = null;
        Main.loginPage.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void openAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAccountActionPerformed
        String accountNumber = (String)accountComboBox.getSelectedItem();
        int selectedIndex = accountComboBox.getSelectedIndex();
        //int accountNumber;
        if(selectedIndex!=0){
            try{
                //accountNumber = Integer.parseInt(accountNumberStr);
                if( Main.accountPage == null){
                    Main.accountPage = new AccountPage();
                }
                Main.accountPage.setAccountDetails(accountNumber,username);
                Main.accountPage.repaint();
                Main.accountPage.setVisible(true);
                Main.userPage.setVisible(false);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Select A valid account Number", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_openAccountActionPerformed
    /*public void accountButtonActionPerformed(java.awt.event.ActionEvent evt){
        javax.swing.JButton accountButton = (javax.swing.JButton)evt.getSource();
        String accountNumber = accountButton.getText();
        if (accountNumber == null) System.out.println("Account Button retuned NuLL");
        if( Main.accountPage == null){
            Main.accountPage = new AccountPage();
        }
        Main.accountPage.setAccountDetails(accountNumber,username);
        Main.accountPage.repaint();
        Main.accountPage.setVisible(true);
        Main.userPage.setVisible(false);
        
    }*/
    
    private String username;
    private String name;
    private String address;
    private int customerId;
    private int numAccounts;
    private javax.swing.DefaultComboBoxModel<String> accountListModel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountComboBox;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressText;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton openAccount;
    private javax.swing.JLabel selectAccountText;
    // End of variables declaration//GEN-END:variables
}
