import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author uthar
 */
public class UserReg extends javax.swing.JFrame {
      Connection connect;
      public UserReg() {
          initComponents();
          //connect=Main.conn();
      }
    /**
     * Creates new form UserReg
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        createUserNameIcon = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        createUsernameLabel = new javax.swing.JLabel();
        createPasswordText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        addressText = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        PHONENO = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ADDRESS = new javax.swing.JTextArea();
        GETUSERNAME = new javax.swing.JTextField();
        SUBMIT = new javax.swing.JButton();
        nameIcon = new javax.swing.JLabel();
        phoneNo = new javax.swing.JLabel();
        emailIcon = new javax.swing.JLabel();
        addressIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        GETPASSWORD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("USER REGISTRATION FORM");

        nameLabel.setText("NAME");

        createUserNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        phoneNumberLabel.setText("PHONE NO");

        createUsernameLabel.setText("CREATE USERNAME");

        createPasswordText.setText("CREATE PASSWORD");

        emailText.setText("E-MAIL");

        addressText.setText("ADDRESS");

        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });

        ADDRESS.setColumns(20);
        ADDRESS.setRows(5);
        jScrollPane1.setViewportView(ADDRESS);

        SUBMIT.setText("SUBMIT");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });

        nameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/username1.png"))); // NOI18N

        phoneNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/phone.png"))); // NOI18N

        emailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mail.png"))); // NOI18N

        addressIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address.png"))); // NOI18N

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pass.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createUserNameIcon)
                            .addComponent(phoneNo)
                            .addComponent(nameIcon)
                            .addComponent(emailIcon)
                            .addComponent(addressIcon))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailText)
                            .addComponent(addressText)
                            .addComponent(createUsernameLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordIcon)
                        .addGap(18, 18, 18)
                        .addComponent(createPasswordText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SUBMIT)
                    .addComponent(NAME)
                    .addComponent(PHONENO)
                    .addComponent(EMAIL)
                    .addComponent(GETUSERNAME)
                    .addComponent(jScrollPane1)
                    .addComponent(GETPASSWORD))
                .addContainerGap(97, Short.MAX_VALUE))
            .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameIcon)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumberLabel)
                        .addComponent(PHONENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailIcon)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailText)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addressIcon)
                        .addComponent(addressText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createUsernameLabel)
                        .addComponent(GETUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createUserNameIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createPasswordText)
                            .addComponent(GETPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(SUBMIT))
                    .addComponent(passwordIcon))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        
        if(verifyInput()){
            String name=NAME.getText();
            String phoneno=PHONENO.getText();
            String email=EMAIL.getText();
            String address=ADDRESS.getText();
            String username=GETUSERNAME.getText();
            String password=GETPASSWORD.getText();

            try{
                String query= "insert into LOGINTAB values(?,?,?)";
                PreparedStatement ps=Main.conn.prepareStatement(query);
                ps.setString(1,username);
                ps.setString(2,password);
                ps.setString(3,"CUST");
                ps.execute();

                ps = Main.conn.prepareStatement("INSERT INTO CUSTOMER(CUS_NAME,CUS_ADDRESS,USERNAME,EMAIL,PHONE) VALUES (?,?,?,?,?)");
                ps.setString(1,name);
                ps.setString(2,address);
                ps.setString(3,username);
                ps.setString(4,email);
                ps.setString(5,phoneno);
                ps.execute();

                this.dispose();
            }catch(Exception ex){
                System.out.println(ex);

            }
        }
    }//GEN-LAST:event_SUBMITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new UserReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ADDRESS;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JPasswordField GETPASSWORD;
    private javax.swing.JTextField GETUSERNAME;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PHONENO;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JLabel addressIcon;
    private javax.swing.JLabel addressText;
    private javax.swing.JLabel createPasswordText;
    private javax.swing.JLabel createUserNameIcon;
    private javax.swing.JLabel createUsernameLabel;
    private javax.swing.JLabel emailIcon;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameIcon;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JLabel phoneNumberLabel;
    // End of variables declaration//GEN-END:variables

    private boolean verifyInput() {
        String name=NAME.getText();
        String phoneno=PHONENO.getText();
        String email=EMAIL.getText();
        String address=ADDRESS.getText();
        String username=GETUSERNAME.getText();
        char[] password=GETPASSWORD.getPassword();
        String passStr = String.valueOf(password);
        if(name.equals("")||username.equals("")||phoneno.equals("")||email.equals("")||address.equals("")||passStr.equals("")){
            JOptionPane.showMessageDialog(this, "All the fields are compulsory", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(phoneno.length()!=10){
            JOptionPane.showMessageDialog(this, "Phone number must be of length 10","Error", JOptionPane.ERROR_MESSAGE);return false;
        }
        if(passStr.length()<=6){
            JOptionPane.showMessageDialog(this, "Password must be of atleast 7 charecters", "Error", JOptionPane.ERROR_MESSAGE);return false;
        }
        if(username.length()<=6){
            JOptionPane.showMessageDialog(this, "Username must be of atleast 7 charecters", "Error", JOptionPane.ERROR_MESSAGE);return false;
        }
        Pattern emailPat = Pattern.compile("[\\w|\\.|d]+@\\w+\\.\\w+");
        Matcher matcher = emailPat.matcher(email);
        if(!matcher.find()){
            JOptionPane.showMessageDialog(this, "Enter a proper email addrress", "Error", JOptionPane.ERROR_MESSAGE);return false;
        }
          try {
              Statement st = Main.conn.createStatement();
              ResultSet rs = st.executeQuery("SELECT USERNAME FROM LOGINTAB WHERE USERNAME = \""+username+"\"");
              if (rs.next()){
                  JOptionPane.showMessageDialog(this, "Username already in use", "Error", JOptionPane.ERROR_MESSAGE);return false;
              }
              rs.close();
              rs = st.executeQuery("SELECT * FROM CUSTOMER WHERE EMAIL = \""+email+"\"");
              if (rs.next()){
                  JOptionPane.showMessageDialog(this, "Email already in use", "Error", JOptionPane.ERROR_MESSAGE);return false;
              }
              rs.close();
              rs = st.executeQuery("SELECT * FROM CUSTOMER WHERE PHONE = \""+phoneno+"\"");
              if (rs.next()){
                  JOptionPane.showMessageDialog(this, "Email already in use", "Error", JOptionPane.ERROR_MESSAGE);return false;
              }
              st.close();
          } catch (SQLException ex) {
              Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        return true;
    }
}
